test/misc.js, test/models/model.js, test/templates/misc/multipleVariables.html
This is somewhat achieved in looping but it is better to have a separate test for this.
=> Added simple unit test to test multiple variables in a template.

test/conditionals.js, test/templates/conditionals/ifNotPresent.html
Prints 'false' when an if statement is untrue
=> test if statement for data not present

test/includes.js, test/templates/includes/argVariableWithinArg.html
This causing an infinite loop and no tests will progress
=> test printing variable of argument within argument

test/conditionals.js, test/templates/conditionals/oneLineFalse.html
This renders as `<p false></p>`
=> test one line if for false condition

test/looping.js, test/templates/looping/noMarkupLoop.html
=> test looping without nested markup

test/looping.js, test/templates/looping/numericalVal.html
results in `<p>{5}</p><p>{5}</p><p>{5}</p>`
=> test loop with number as val

test/conditionals.js, test/templates/conditionals/ifEscapeRegex.html
comes up as:
```
<input type='text' name='date' placeholder='DD/MM/YYYY' id='date' pattern='^(3[0-1]|[1-2]\d|[1-9]|0\d)\/(1[0-2]|[1-9]|0\d)\/[1-2]\d{3}
>
```
=> test evaluating conditional that contains regex pattern

test/looping.js, test/models/model.js, test/templates/looping/camelCaseLoopVal.html
=> test using a camelCase loop val

test/includes.js, test/templates/includes/inlineScriptTag.html
=> test escaping contents of script tag

test/client.html, test/conditionals.js, test/templates/conditionals/duplicateOperatorInline.html, test/templates/conditionals/duplicateVarInline.html
These two tests supply coverage for #24 
They both pass
=> tests for duplicate vars and operators inline

test/client.html, test/conditionals.js, test/templates/conditionals/ifElseRegex.html
=> Test evaluating if else where if contains regex pattern

test/client.html, test/includes.js, test/templates/includes/includeInvalidTemplate.html
Evaluates as `<div> noExist </div>`
=> test for including nonexistant template

.eslintignore, package.json, test/client.html, test/conditionals.js, test/includes.js, test/looping.js, test/misc.js, test/templates/looping/loopInvalidAttributes.html
This will also print some warnings in the console to increase code coverage
=> test loops with invalid markup

teddy.js
Fixed loss of HTML attribute data that appears after inline if conditionals when they are rendered.
=> Fixed Data Loss Issue in Inline If Conditionals

test/conditionals.js, test/templates/conditionals/oneLineValueWithAdditionalAttributesNotImpactedByIf.html
Feel free to change spacing or whatever as you feel fit
=> Added unit test one line if with value and always occurring attributes regardless of if check

package.json
This PR:
-  Uses husky to check if stagged files are using valid lint rules
- Does unit test with precommit script
=> Add husky precommit to teddy

README.md, package.json, teddy.js, test/misc.js, test/templates/misc/varNoParsing.html
=> closes #160

package-lock.json, teddy.js, test/conditionals.js, test/templates/conditionals/ifOutsideIf.html, test/templates/conditionals/nestedIfOutsideIf.html, test/templates/conditionals/oneLineIfOutsideIf.html, test/templates/conditionals/oneLineIfOutsideIfReverse.html, test/templates/conditionals/varIfOutsideIf.html
Fixed #166 
Implemented recursive match so nesting works whether or not 'if-' should be parsed.
Added some test templates and their accompanying unit tests to make sure other features do not break:
* `test/templates/conditionals/ifOutsideIf.html`
* ` test/templates/conditionals/nestedIfOutsideIf.html`
* `test/templates/conditionals/oneLineIfOutsideIf.html`
* `test/templates/conditionals/oneLineIfOutsideIfReverse.html` 
* `test/templates/conditionals/varIfOutsideIf.html`
=> isolated if- parse bug

teddy.js, test/conditionals.js, test/templates/conditionals/ifCommentElse.html, test/templates/conditionals/ifMultipleCommentsElse.html
=> Fix else conditions failing with preceding comment bug

package-lock.json, teddy.js, test/conditionals.js, test/templates/conditionals/unlessNestedElse.html, test/templates/conditionals/unlessNestedIf.html, test/templates/conditionals/unlessNestedIfWithComment.html, test/templates/conditionals/unlessWithComment.html
closes https://github.com/rooseveltframework/teddy/pull/230
closes https://github.com/rooseveltframework/teddy/pull/229
closes https://github.com/rooseveltframework/teddy/pull/226
=> Fix else condition tag mismatch

.eslintignore, .gitignore, .istanbul.yml, .travis.yml, appveyor.yml, package-lock.json, package.json, teddy.js
- Audit devDependencies
- Audit scripts
- Add node 8-10 to appveyor and travis configs + cleanup
- Remove .eslintignore
- Replace istanbul with nyc (Closes #222)
- Add eslint for linting exclusive mocha tests
=> Full CI and script audit

package-lock.json, package.json, test/includes.js, test/misc.js, test/models/model.js
This pull request:
- Updates ESlint
- Updates Standard
- Lints against standard
=> Updates for ESlint and Standard

README.md
http://bradfrost.com/blog/post/just/
=> README copyediting

package.json
=> Take linting out of "test" script

package-lock.json, package.json, teddy.js
- Update dependency standard to v13
- Update dependency lint-staged to v9
=> update standard to v13 and lint-stagged to 9.2.0

looping.js, package-lock.json, test/conditionals.js, test/looping.js, test/misc.js, test/templates/looping/loopNoVal.html, test/templates/looping/nestedObjects.html, utils.js
Fixes #446, #431, #449, #426
oneLineInLoop
- Logic that looks for olifs in loops wasn't hitting the conditional correctly since characters are read backwards (instead of looking for ' if-' we look for '-fi ')
nestedObjects
- Find context uses a prestored string containing an index for grabbing values. In the case of an object of objects, we now convert it into a list of values first before getting the value from index to prevent an undefined value.
serverSideCommentsWithTeddyCode
- Logic for assessing nested loops was getting hit even though tags were inside a teddy comment block, now we check for whether or not we are in a comment before assessing <loop> within <loop>
loopNoVal
- Logic for requiring val attribute in loop no longer necessary, now we require either a key or val attribute …
=> Teddy bug fixes

package-lock.json, package.json, test/misc.js
Some tests written against playground.js, using playwright. Addresses #209 
Also incorporates #472
=> Playground tests

test/conditionals.js, test/templates/conditionals/ifCommentsEmbedded.html
=> Added new Unit Test to test conditionals with embedded HTML comment

conditionals.js, test/looping.js, test/models/model.js, test/templates/looping/nestedLoopsObjectWithArrayOfObjects.html
=> Broken test for nested loop through object with array of objects

looping.js, package.json, test/looping.js
(looping/nestedLoopsObjectWithArrayOfObjects.html)
=> Resolved test 'should parse nested loops correctly'

looping.js, test/looping.js
Test is now passing without causing any other test to fail.
Fixed linters as well.
=> Bug fix #574

looping.js, test/looping.js
Was able to pass the test without effecting any other test case. 
Fixed linters.
=> Bug fix #581

looping.js, test/looping.js
test is now passing without causing other test cases to fail.
=> Was able to resolve bug #583

looping.js, test/looping.js
Was able to fix the bug without causing any other crashes.
=> Bug fix #585

cheerioPolyfill.js, test/loaders/playwright.js, test/tests.js
this tests all files the webpack bundler generates to ensure they are bundled correctly
=> added more tests
